architect/architect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]

architect/core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'core'
urlpatterns = [
    path("home/", views.core_home, name="home"),
    path("about/", views.core_about, name="about"),
    path("contact/", views.core_contact, name="contact"),
    path("gallery/", views.core_gallery, name="gallery"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

architect/core/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100,default='Empty')
    image = models.ImageField(upload_to="uploads/")
    description = models.CharField(max_length=250,default='')
    
    def __str__(self) -> str:
        return self.title

architect/core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project


# Create your views here.
def core_home(request):
    return render(request,'core/index.html')


def core_contact(request):
    return render(request,'core/contact.html')


def core_about(request):
    return render(request,'core/about.html')

def core_gallery(request):
    projects = Project.objects.all()
    context = {
        'projects':projects
    }
    return render(request,'core/gallery.html',context=context)

architect/core/templates/core/about.html
{% extends "core/base.html" %} {% block title %} About {% endblock %} 
{% block content %}
<div class="bg-zinc-800 py-4 w-3/4 md:w-3/5 rounded-3xl px-12 pt-8 pb-12">
  <div class="w-full text-center text-white text-lg font-bold">
    <p class="mb-2 md:text-5xl text-2xl py-4">About</p>
  </div>
  <div class="text-center text-white text-xs md:text-lg mx-auto md:text-normal">
    <p class="leading-6 md:leading-10 text-center">
      Welcome to the online home of Joseph M Hyland, an architect based in South
      River, NJ, serving the architectural needs of Central Jersey and beyond...
    </p>
  </div>
  <div class="w-full text-center text-white text-lg font-bold">
    <p class="mb-2 md:text-2xl py-4">Our Story</p>
  </div>
  <div class="text-center text-white text-xs md:text-lg mx-auto md:text-normal">
    <p class="leading-6 md:leading-10 text-center">
      We bring a unique blend of passion, creativity, and expertise to every
      project. With a deep-rooted commitment to innovation and sustainability,
      we strive to push the boundaries of traditional architecture, creating
      spaces that inspire and endure.
    </p>
  </div>

  <div class="w-full text-center text-white text-lg font-bold">
    <p class="mb-2 md:text-2xl py-4">Expertise</p>
  </div>
  <div class="text-center text-white text-xs md:text-lg mx-auto md:text-normal">
    <p class="leading-6 md:leading-10 text-center">
      With years of experience in the field, We have successfully completed a
      diverse range of projects, spanning residential, commercial,
      institutional, and cultural sectors. From sleek modern designs to historic
      preservation, our portfolio showcases our dedication to excellence and
      attention to detail.
    </p>
  </div>
  <div class="w-full text-center text-white text-lg font-bold">
    <p class="mb-2 md:text-2xl py-4">Teaching Experience</p>
  </div>
  <div class="text-center text-white text-xs md:text-lg mx-auto md:text-normal">
    <p class="leading-6 md:leading-10 text-center">
      In addition to our professional practice, We are proud to have served as a
      teacher at Rutgers University, sharing our knowledge and insights with the
      next generation of architects. This experience has not only enriched our
      understanding of the field but also reinforced our commitment to education
      and mentorship.
    </p>
  </div>
  <div class="w-full text-center text-white text-lg font-bold">
    <p class="mb-2 md:text-2xl py-4">Commitment to Community</p>
  </div>
  <div class="text-center text-white text-xs md:text-lg mx-auto md:text-normal">
    <p class="leading-6 md:leading-10 text-center">
      As a local architect, We are deeply invested in the communities we serve.
      We believe in the transformative power of architecture to enhance the
      quality of life and foster connections within neighborhoods. Whether
      revitalizing urban spaces or designing sustainable homes, we approach each
      project with a deep sense of responsibility and dedication to making a
      positive impact.
    </p>
  </div>
  <div
    class="w-full text-center text-white text-lg font-bold"
    class="w-full text-center text-white text-lg font-bold"
    class="w-full text-center text-white text-lg font-bold"
  >
    <p class="mb-2 md:text-2xl py-4">Get in Touch</p>
  </div>
  <div class="text-center text-white text-xs md:text-lg mx-auto md:text-normal">
    <p class="leading-6 md:leading-10 text-center">
      Explore our portfolio to discover our past projects and envision the
      possibilities for your next venture. We welcome collaborations with
      clients who share our vision for bold, innovative design. Contact us today
      to discuss how we can bring your architectural dreams to life.
    </p>
  </div>

</div>
{% endblock %}

architect/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../static/styles.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap"
      rel="stylesheet"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap"
      rel="stylesheet"
    />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Joseph M Hyland | {% block title %} {% endblock %}</title>
    <script>
      tailwind.config = {
        theme: {
          extend: {
            colors: {
              yellow: "#fde047",
            },
            fontFamily: {
              sans: ["Graphik", "sans-serif"],
              serif: ["Merriweather", "serif"],
              roboto: ["Roboto Condensed", "sans-serif"],
            },
            backgroundImage: {
              "machine-pattern": "url('./images/equip.jpg')",
            },
            screens: {
              sm: "300px",
              // => @media (min-width: 640px) { ... }

              md: "768px",
              // => @media (min-width: 768px) { ... }

              lg: "1024px",
              // => @media (min-width: 1024px) { ... }

              xl: "1280px",
              // => @media (min-width: 1280px) { ... }

              "2xl": "1536px",
              // => @media (min-width: 1536px) { ... }
            },
          },
        },
      };
    </script>    
    {% load static %}
    <style>
      .image-container {
        background-image: url("{% static 'core/residential_1.png' %}");
        background-size: cover; /* Adjust as needed */
        background-position: center; /* Adjust as needed */
      }
      .jetbrains-mono {
        font-family: "JetBrains Mono", monospace;
        font-optical-sizing: auto;
        font-weight: <weight>;
        font-style: normal;
      }
      .inter {
        font-family: "Inter", sans-serif;
        font-optical-sizing: auto;
        font-weight: <weight>;
        font-style: normal;
        font-variation-settings: "slnt" 0;
      }
    </style>
  </head>
  <body class="w-full min-h-screen text-white flex flex-col justify-between gap-6 image-container bg-fixed inter">
    <header>
      <div class="h-16 bg-zinc-800 flex justify-between items-center px-4">
        <a href="{% url 'core:home' %}"><div class="text-center text-white md:text-3xl font-normal jetbrains-mono">
          JOSEPH M HYLAND
        </div></a>
        <div id="tempBox"></div>
        <div class="hidden lg:hidden" id="headerBtn">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="white"
            class="w-6 h-6"
          >
            <path
              fill-rule="evenodd"
              d="M3 6.75A.75.75 0 0 1 3.75 6h16.5a.75.75 0 0 1 0 1.5H3.75A.75.75 0 0 1 3 6.75ZM3 12a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5H3.75A.75.75 0 0 1 3 12Zm0 5.25a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5H3.75a.75.75 0 0 1-.75-.75Z"
              clip-rule="evenodd"
            />
          </svg>
        </div>
        <div class="flex gap-2">
          <a href="{% url 'core:home' %}"><div
            class="text-center text-white text-xs md:text-xl jetbrains-mono "
          >
            HOME
          </div></a>
          <a href="{% url 'core:about' %}"><div
            class="text-center text-white text-xs md:text-xl jetbrains-mono "
          >
            ABOUT
          </div></a>
          <a href="{% url 'core:contact' %}"><div
            class="text-center text-white text-xs md:text-xl jetbrains-mono "
          >
            CONTACT
          </div></a>
          <a href="{% url 'core:gallery' %}"><div
            class="text-center text-white text-xs md:text-xl jetbrains-mono "
          >
            GALLERY
          </div></a>
        </div>
      </div>
    </header>
    <main class="flex justify-center items-center">
        {% block content %}{% endblock %}
     </main>
     <footer class="bg-zinc-800">
      <div class="text-center">
        <p class="text-xs md:text-lg jetbrains-mono">JOSEPH M HYLAND</p>
      </div>
    </footer>
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <script src="../static/js/contact.js"></script>
    <script src="{% static 'core/header.js' %}"></script>
  </body>

</html>

architect/core/templates/core/base_home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../static/styles.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap"
      rel="stylesheet"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap"
      rel="stylesheet"
    />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Joseph M Hyland | {% block title %}{% endblock %}</title>
    {% load static %}
    <script>
      tailwind.config = {
        theme: {
          extend: {
            colors: {
              yellow: "#fde047",
            },
            fontFamily: {
              sans: ["Graphik", "sans-serif"],
              serif: ["Merriweather", "serif"],
              roboto: ["Roboto Condensed", "sans-serif"],
            },
            screens: {
              sm: "300px",
              // => @media (min-width: 640px) { ... }

              md: "768px",
              // => @media (min-width: 768px) { ... }

              lg: "1024px",
              // => @media (min-width: 1024px) { ... }

              xl: "1280px",
              // => @media (min-width: 1280px) { ... }

              "2xl": "1536px",
              // => @media (min-width: 1536px) { ... }
            },
          },
        },
      };
    </script>
        {% load static %}
    <style>
      .image-container {
        background-image: url("{% static 'core/residential_1.png' %}");
        background-size: cover; /* Adjust as needed */
        background-position: center; /* Adjust as needed */
      }
      .jetbrains-mono {
        font-family: "JetBrains Mono", monospace;
        font-optical-sizing: auto;
        font-weight: <weight>;
        font-style: normal;
      }
      .inter {
        font-family: "Inter", sans-serif;
        font-optical-sizing: auto;
        font-weight: <weight>;
        font-style: normal;
        font-variation-settings: "slnt" 0;
      }
    </style>
  </head>
  <body class="w-full min-h-screen text-white flex flex-col  justify-between bg-zinc-800 inter">
    <header>
      <div class="h-16 bg-zinc-800 flex justify-between items-center px-4">
        <a href="{% url 'core:home' %}"><div class="text-center text-white md:text-3xl font-normal jetbrains-mono">
          JOSEPH M HYLAND
        </div></a>
        <div class="hidden lg:hidden" id="headerBtn">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="white"
            class="w-6 h-6"
          >
            <path
              fill-rule="evenodd"
              d="M3 6.75A.75.75 0 0 1 3.75 6h16.5a.75.75 0 0 1 0 1.5H3.75A.75.75 0 0 1 3 6.75ZM3 12a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5H3.75A.75.75 0 0 1 3 12Zm0 5.25a.75.75 0 0 1 .75-.75h16.5a.75.75 0 0 1 0 1.5H3.75a.75.75 0 0 1-.75-.75Z"
              clip-rule="evenodd"
            />
          </svg>
        </div>
        <div class="flex gap-2">
          <a href="{% url 'core:home' %}"><div
            class="text-center text-white text-xs md:text-xl jetbrains-mono "
          >
            HOME
          </div></a>
          <a href="{% url 'core:about' %}"><div
            class="text-center text-white text-xs md:text-xl jetbrains-mono "
          >
            ABOUT
          </div></a>
          <a href="{% url 'core:contact' %}"><div
            class="text-center text-white text-xs md:text-xl jetbrains-mono "
          >
            CONTACT
          </div></a>
          <a href="{% url 'core:gallery' %}"><div
            class="text-center text-white text-xs md:text-xl jetbrains-mono "
          >
            GALLERY
          </div></a>
        </div>
      </div>
    </header>
    <main>
      {% block content %}{% endblock %}
    </main>
    <footer class="bg-zinc-800">
      <div class="text-center">
        <p class="text-xs md:text-lg jetbrains-mono">JOSEPH M HYLAND</p>
      </div>
    </footer>
  </body>
</html>

architect/core/templates/core/contact.html
{% extends 'core/base.html' %}
{% block title %} Contact {% endblock %}
{% block content %}
      <div class="bg-zinc-800 py-4 w-3/4 md:w-3/5 rounded-3xl px-12 pt-8 pb-12">
        <div
          class="w-full text-center text-white text-lg font-bold"
        >
          <p class="mb-2 md:text-5xl text-2xl  py-4" >Contact </p>
        </div>
        <div
          class="text-center text-white text-xs md:text-lg mx-auto md:text-normal "
        >
        <p class="leading-6 md:leading-10 text-center">
          Thank you for your interest. We look forward to connecting with you and discussing how we can bring your architectural vision to life. Please feel free to reach out to us using the contact information provided below, or fill out the inquiry form, and we'll get back to you as soon as possible.
        </p>
        <div class="md:grid grid-cols-2 py-12">
        <div class="text-start flex flex-col gap-6">
          <div><p class="text-center text-2xl">Address</p></div>
          <p>Address: 77 Milltown Rd, East Brunswick, NJ 08816</p>
          <p>Phone: +1 (732)-698-1795</p>
          <p>Email: josephmhyland@gmail.com</p>
          <p>Social Media: <a href="https://www.facebook.com/search/top?q=joseph%20m%20hyland%20architect" > <span class="text-blue">Facebook</span></a></p>
          <!-- <p>Inquiry Form</p>
          <p>[Form Placeholder]</p> -->
        </div>
        <div class="text-start md:flex flex-col gap-6 ">
          <div><p class="text-center text-2xl">Map</p></div>
          <div><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3036.5553535188897!2d-74.40080582451579!3d40.440843754172136!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c3cf5c0c4d0c39%3A0xdabdd418ad06cd57!2sHyland%20Joseph!5e0!3m2!1sen!2sus!4v1713321620000!5m2!1sen!2sus" width="300" height="225" style="border:0; margin: auto;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>
        </div>

          
        </div>
        <div class="text-start flex flex-col gap-6">
        <p class="text-center text-2xl">Office Hours</p>
        <p class="text-center">Monday - Friday: 9:00 am - 5:30 pm</p>
        <p class="text-center">Saturday - Saturday: Closed</p>
      </div>
      </div>
      <div>

{% endblock %}

architect/core/templates/core/gallery.html
{% extends 'core/base.html' %}
{% block title %} Gallery {% endblock %}
{% block content %}

<div class="bg-zinc-800 py-4 w-3/4 md:w-3/4 rounded-3xl px-6 pt-8 pb-12 ">
    <div
    class="w-full text-center text-white text-lg font-bold"
  >
    <p class="mb-2 md:text-5xl text-2xl  py-4" >Gallery </p>
  </div>
  <div class="grid md:grid-cols-3 gap-4">
    {% for project in projects %}

        <div class="flex justify-center"><img class="h-40 md:h-80 w-52 md:w-80 rounded-3xl" src="{{project.image.url}}" alt=""></div>
    {% endfor %}
</div>
</div>

{% endblock %}

architect/core/templates/core/index.html


{% extends 'core/base_home.html' %}
{% block title %} Index {% endblock %}
{% block content %}
{% load static %}
<div
  class="image-container h-[250px] md:h-[600px] top-0 flex justify-center items-center text-white text-xl"
>
  <div class="">
    <p class="text-center text-xl md:text-6xl font-extrabold">
      From Concept to Construction, <br />
      We're with You Every Step
    </p>
  </div>
</div>
<div class="bg-zinc-800 py-6">
  <div class="w-full text-center text-white text-lg font-bold">
    <p class="mb-2 md:text-3xl py-6">ARCHITECT AND PLANNER</p>
  </div>
  <div
    class="w-3/4 md:w-3/5 text-center text-white text-xs md:text-lg font-normal mx-auto"
  >
    <p class="leading-6 md:leading-10">
      An accomplished architect and urban planner specialized in the design and
      construction of exceptional buildings, with a rich portfolio boasting over
      a thousand successful projects. With a keen eye for detail and a passion
      for innovative design, I bring over 20 years of expertise to every
      project, ensuring that each structure is not only visually striking but
      also functionally superior.
    </p>
  </div>
</div>
<div class="bg-slate-400   md:flex" ><img class="md:w-1/2" src="{% static 'core/frame.jpg' %}" alt="">
  <img class="md:w-1/2 hidden md:block"src="{% static 'core/final.jpg' %}" alt=""></div>
<div class="bg-zinc-800 py-4">
  <div class="w-full text-center text-white text-lg font-bold">
    <p class="mb-2 md:text-3xl py-4">AREAS OF WORK</p>
  </div>
  <div
    class="w-3/4 md:w-3/5 text-center text-white text-xs md:text-lg mx-auto md:text-normal py-6"
  >
    <p class="leading-6 md:leading-10">
      From iconic landmarks to bespoke residential dwellings, my commitment to
      excellence and dedication to pushing the boundaries of architectural
      possibility have earned me a reputation as a trusted visionary in the
      industry.
    </p>
  </div>
  <div class="grid grid-cols-3 py-4">
    <div
      class="flex flex-col justify-center text-sm md:text-2xl font-extrabold items-center"
    >
      <p>COMMERCIAL</p>
      <div class="w-24 md:w-80 py-2 hover:opacity-80 hover:cursor-pointer">
        <img class="rounded-xl" src="{% static 'core/commercial.jpg' %}" alt="" />
      </div>
    </div>
    <div
      class="flex flex-col justify-center text-sm md:text-2xl font-extrabold items-center"
    >
      <p>RESIDENTIAL</p>
      <div class="w-24 md:w-80 py-2 hover:opacity-80 hover:cursor-pointer">
        <img class="rounded-xl" src="{% static 'core/residential.jpg' %}" alt="" />
      </div>
    </div>
    <div
      class="flex flex-col justify-center text-sm md:text-2xl font-extrabold items-center"
    >
      <p>INDUSTRIAL</p>
      <div class="w-24 md:w-80 py-2 hover:opacity-80 hover:cursor-pointer">
        <img class="rounded-xl" src="{% static 'core/industrial.jpg' %}" alt="" />
      </div>
    </div>
  </div>
</div>
{% endblock %}